// TODO(Antigravity): implement per seo/PLAN-antigravity-brief.md — WS1 City hub pages
// Purpose: canonical city list, slugify, and misspelling-alias map for /city/* routes.
// 1. Define CityEntry { name, slug, state, districts: string[], pincodeCount, priority }
// 2. Load entries from src/data/cities.json (generated by scripts/build-city-index.mjs)
// 3. getCityBySlug(slug), getAllCities() (sorted by priority desc), slugify(name)
// 4. ALIASES: misspellings -> canonical slug, e.g. banglore->bangalore, ahemdabad->ahmedabad,
//    trivandrum->thiruvananthapuram, tirupur->tiruppur, gurgaon/gurugram->gurgaon
// 5. Keywords for priority come from seo/gsc-pincode-keywords.csv (search_interest desc)
export interface CityEntry {
  name: string;
  slug: string;
  state: string;
  districts: string[];
  pincodeCount: number;
  priority: number;
}

// TODO: implement loadCities(), getCityBySlug(), getAllCities(), slugify(), ALIASES
export const ALIASES: Record<string, string> = {};
export function getCityBySlug(_slug: string): CityEntry | null {
  // TODO(Antigravity)
  return null;
}
export function getAllCities(): CityEntry[] {
  // TODO(Antigravity)
  return [];
}
