-- Digipincode — D1 schema
-- Tables: states, districts, sub_districts, villages, pincodes, lgd_panchayats, digipin, feedback

CREATE TABLE IF NOT EXISTS states (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT UNIQUE NOT NULL,          -- e.g. 'PB'
  name TEXT NOT NULL,
  name_hi TEXT,
  slug TEXT UNIQUE NOT NULL           -- e.g. 'punjab'
);

CREATE TABLE IF NOT EXISTS districts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  state_id INTEGER NOT NULL REFERENCES states(id),
  code TEXT,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  UNIQUE(state_id, slug)
);

CREATE TABLE IF NOT EXISTS sub_districts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  district_id INTEGER NOT NULL REFERENCES districts(id),
  code TEXT,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  UNIQUE(district_id, slug)
);

CREATE TABLE IF NOT EXISTS villages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sub_district_id INTEGER NOT NULL REFERENCES sub_districts(id),
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  pincode TEXT,
  census_code TEXT,
  lgd_code TEXT,
  population INTEGER,
  households INTEGER,
  lat REAL,
  lon REAL,
  digipin TEXT,                       -- 10-digit Digital Postal Index (DIGIPIN)
  ai_description TEXT,                -- generated by skm-ai-worker
  UNIQUE(sub_district_id, slug)
);

CREATE TABLE IF NOT EXISTS pincodes (
  pincode TEXT PRIMARY KEY,
  office_name TEXT,
  office_type TEXT,                   -- BO/SO/HO
  district_id INTEGER REFERENCES districts(id),
  state_id INTEGER REFERENCES states(id),
  delivery TEXT,
  division TEXT,
  region TEXT,
  circle TEXT,
  taluk TEXT,
  lat REAL,
  lon REAL,
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS lgd_panchayats (
  lgd_code TEXT PRIMARY KEY,          -- LGD local body code
  state_lgd_code TEXT,
  district_lgd_code TEXT,
  block_lgd_code TEXT,
  local_body_name TEXT NOT NULL,
  local_body_type TEXT,               -- Gram Panchayat / Block Panchayat / Zilla Parishad
  state_name TEXT,
  district_name TEXT,
  block_name TEXT,
  village_lgd_code TEXT,
  census_code TEXT,
  population INTEGER,
  households INTEGER,
  area_km2 REAL,
  head_name TEXT,
  head_phone TEXT,
  website TEXT,
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS digipin (
  digipin TEXT PRIMARY KEY,           -- e.g. '492FJT6M7C'
  lat REAL NOT NULL,
  lon REAL NOT NULL,
  pincode TEXT,
  village_id INTEGER REFERENCES villages(id),
  accuracy TEXT DEFAULT 'high',       -- high/medium/low
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS feedback (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL,                 -- 'feature' | 'update'
  message TEXT NOT NULL,
  email TEXT,
  url TEXT,
  status TEXT DEFAULT 'new',          -- new / reviewed / done
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_villages_pincode ON villages(pincode);
CREATE INDEX IF NOT EXISTS idx_villages_slug ON villages(slug);
CREATE INDEX IF NOT EXISTS idx_districts_state ON districts(state_id);
CREATE INDEX IF NOT EXISTS idx_subdistricts_district ON sub_districts(district_id);
CREATE INDEX IF NOT EXISTS idx_pincodes_state ON pincodes(state_id);
CREATE INDEX IF NOT EXISTS idx_lgd_state ON lgd_panchayats(state_name);
CREATE INDEX IF NOT EXISTS idx_lgd_district ON lgd_panchayats(district_name);