-- Seed batch 2 (18 Sep 2026): Chhath city pages LIVE + mapsnearme keyword set.
-- Idempotent: INSERT OR IGNORE.

-- ===== CHHATH EXPANSION (digipincode — 39 city pages live, arghya timings added) =====
INSERT OR IGNORE INTO keywords (site, keyword, intent, cluster, target_url, status, notes) VALUES
('digipincode','chhath puja 2026','info','seasonal','/chhath/','created','Head term — hub page live, huge seasonal spike Nov.'),
('digipincode','chhath puja 2026 dates','info','seasonal','/chhath/','created','13-16 Nov 2026 — dates table on hub page.'),
('digipincode','chhath puja 2026 date kab hai','info','seasonal','/chhath/','created','Hindi phrasing — same intent.'),
('digipincode','chhath puja kab hai 2026','info','seasonal','/chhath/','created','Hindi variant.'),
('digipincode','chhath puja ghats in patna','info','seasonal','/chhath/patna','created','Highest-volume city page — Patliputra, Gandhi Ghat etc.'),
('digipincode','chhath puja ghats in delhi','info','seasonal','/chhath/delhi','created','17 model ghats — Yamuna reopened 2025.'),
('digipincode','chhath ghat list varanasi','info','seasonal','/chhath/varanasi','created','Assi, Dashashwamedh — 3 lakh+ crowd intent.'),
('digipincode','chhath puja ghats lucknow','info','seasonal','/chhath/lucknow','created','Gomti ghats — 88 sites.'),
('digipincode','chhath puja mumbai ghats','info','seasonal','/chhath/mumbai','created','Juhu epicentre — diaspora heavy.'),
('digipincode','chhath puja bengaluru lakes','info','seasonal','/chhath/bengaluru','created','Ulsoor etc — lake keywords differ from ghat.'),
('digipincode','chhath puja hyderabad ghats','info','seasonal','/chhath/hyderabad','created','Tank Bund flagship.'),
('digipincode','chhath puja ghat near me 2026','info','seasonal','/chhath/','created','Near-me intent — hub + city pages serve.'),
('digipincode','sandhya arghya timing 2026','info','seasonal','/chhath/','created','Timing intent — city pages have computed timings.'),
('digipincode','usha arghya sunrise time 2026','info','seasonal','/chhath/','created','16 Nov sunrise — city-specific timings.'),
('digipincode','chhath puja arghya time [city]','info','seasonal','','planned','PATTERN: timing page per city — computed from coordinates.'),
('digipincode','chhath puja patna ghat advisory','info','seasonal','/chhath/patna','created','Admin banned-ghat list intent — yearly update.'),
('digipincode','chhath ghats in bihar','info','seasonal','/chhath/','created','State rollup — Bihar cities dominate.'),
('digipincode','chhath puja guwahati','info','seasonal','/chhath/guwahati','created','Brahmaputra ghats — NE expansion.'),
('digipincode','chhath puja jaipur galta','info','seasonal','/chhath/jaipur','created','Galta Kund main venue.'),
('digipincode','chhath ghat ranchi list','info','seasonal','/chhath/ranchi','created','74 surveyed ghats — pond keywords.'),
('digipincode','chhath puja kolkata hooghly ghats','info','seasonal','/chhath/kolkata','created','Babughat etc — note Sarobar ban.'),
('digipincode','chhath puja surat tapi ghat','info','seasonal','/chhath/surat','created','Jahangirpura 80k+ — diaspora city.'),
('digipincode','chhath puja ghats in kanpur','info','seasonal','/chhath/kanpur','created','Sarsaiya, Bithoor.'),
('digipincode','chhath puja ghats prayagraj sangam','info','seasonal','/chhath/prayagraj','created','Sangam ghats.'),
('digipincode','chhath puja 2026 kab hai november','info','seasonal','/chhath/','created','November-focused variant.'),
('digipincode','chhath puja dehradun ghats','info','seasonal','/chhath/dehradun','created','22-23 ghats.'),
('digipincode','chhath puja bhopal lakes','info','seasonal','/chhath/bhopal','created','Upper Lake 52 ghats.'),
('digipincode','chhath puja nagpur lakes','info','seasonal','/chhath/nagpur','created','Ambazari main.'),
('digipincode','chhath puja chandigarh lake','info','seasonal','/chhath/chandigarh','created','Sector 42 New Lake.'),
('digipincode','chhath puja ludhiana canal ghat','info','seasonal','/chhath/ludhiana','created','Sidhwan Canal.'),
('digipincode','chhath puja gaya falgu ghat','info','seasonal','/chhath/gaya','created','Falgu dry — kund angle.'),
('digipincode','chhath puja muzaffarpur ghat list','info','seasonal','/chhath/muzaffarpur','created','Budhi Gandak + Sahu Pokhar.'),
('digipincode','chhath puja katihar ganga ghat','info','seasonal','/chhath/katihar','created','Manihari 5 lakh crowd.'),
('digipincode','chhath puja buxar ramrekha ghat','info','seasonal','/chhath/buxar','created','Ramrekha international crowd.'),
('digipincode','chhath puja hajipur kaunhara ghat','info','seasonal','/chhath/hajipur','created','Ganga-Gandak sangam.'),
('digipincode','chhath puja vadodara mahisagar','info','seasonal','/chhath/vadodara','created','Bihar Mandal 20+ years.'),
('digipincode','chhath puja indore ghat list','info','seasonal','/chhath/indore','created','150-200 venues.'),
('digipincode','chhath puja bhubaneswar kuakhai','info','seasonal','/chhath/bhubaneswar','created','Kuakhai main venue.'),
('digipincode','chhath puja jalandhar canal','info','seasonal','/chhath/jalandhar','created','Bist Doab canal.'),
('digipincode','chhath puja chennai marina beach','info','seasonal','/chhath/chennai','created','Marina Beach.'),
('digipincode','nahay khay kharna dates 2026','info','seasonal','/chhath/','created','Day 1-2 ritual queries.'),
('digipincode','chhath puja vidhi samagri list','info','seasonal','','planned','Content gap — samagri list article banti hai.'),
('digipincode','chhath puja song geet list','info','seasonal','','planned','Sharda Sinha songs intent — content gap, traffic heavy.'),
('digipincode','chhath mathar arghya sunrise','info','seasonal','','planned','Bhojpuri phrasing variant.');

-- ===== MAPSNEARME (first keyword set — Phase 4 pages live, internal search logging ON) =====
INSERT OR IGNORE INTO keywords (site, keyword, intent, cluster, target_url, status, notes) VALUES
('mapsnearme','businesses near me','commercial','core','/search','planned','Head term — huge volume, long battle.'),
('mapsnearme','[category] near [city]','commercial','local-combo','/search','planned','PATTERN: core money query — category×city pages isi se serve hoti hain.'),
('mapsnearme','dentist in delhi','commercial','local-combo','/search?q=Dentist&loc=Delhi','planned','Example combo — verify search URL serves.'),
('mapsnearme','restaurant near me [city]','commercial','local-combo','/search','planned','Restaurant cluster.'),
('mapsnearme','best doctor in patna','commercial','local-combo','/search?q=Doctor&loc=Patna','planned','Patna focus — B2B listing claims Phase 2 se.'),
('mapsnearme','verified business directory india','commercial','core','/','planned','Directory intent — homepage serves.'),
('mapsnearme','india business directory with phone number','commercial','core','/','planned','Phone-number angle — humara data USP.'),
('mapsnearme','local business listing india','commercial','core','/','planned','Head term variant.'),
('mapsnearme','[service] in [city] contact number','commercial','local-combo','/search','planned','PATTERN: contact intent — b/[id] pages serve.'),
('mapsnearme','top 10 [category] in [city]','commercial','local-combo','/category/','planned','PATTERN: listicle intent — leaderboard Phase 2 se strong.'),
('mapsnearme','claim your business listing india','transactional','owner','/','planned','Owner acquisition — Phase 2 dashboard funnel.'),
('mapsnearme','free business listing india','transactional','owner','/','planned','Owner signups — free tier pitch.'),
('mapsnearme','advertise on mapsnearme','transactional','monetization','/','planned','Ad sales intent — AdSlot slots live.'),
('mapsnearme','mapsnearme reviews','navigational','brand','/','planned','Brand queries — track growth.'),
('mapsnearme','chhath ghat near me businesses','commercial','seasonal-bridge','/search','planned','Bridge: digipincode Chhath traffic → mapsnearme.'),
('mapsnearme','shop open near me now','commercial','local-combo','/search','planned','Hours intent — future feature.'),
('mapsnearme','[city] local services directory','commercial','local-combo','/search','planned','PATTERN: city directory intent.'),
('mapsnearme','hotels near [landmark]','commercial','local-combo','/search','planned','PATTERN: landmark-based — needs landmark data later.');

-- ===== MAPSNEARME NEGATIVE =====
INSERT OR IGNORE INTO negative_keywords (site, keyword, reason) VALUES
('mapsnearme','google maps customer care number','Google support intent — hum nahi.'),
('mapsnearme','google maps download','Google product intent.'),
('mapsnearme','gps navigation app','Navigation app intent — hum directory hain.'),
('mapsnearme','how to add business on google maps','Google My Business — competitor ka product.'),
('mapsnearme','maps api pricing','Developer intent — nahi serve karte.'),
('mapsnearme','mapsnearme franchise cost','Franchise spam.'),
('mapsnearme','fake business reviews buy','Black-hat intent — kabhi nahi.'),
('mapsnearme','buy google reviews','Black-hat — reject.'),
('mapsnearme','free leads database download','Scraping intent.'),
('mapsnearme','google map api key free','Developer intent.'),
('mapsnearme','maps to the stars song','Entertainment noise.'),
('mapsnearme','world map poster buy','E-commerce intent.'),
('mapsnearme','mapsnearme owner name','Personal info intent — privacy.'),
('mapsnearme','yandex maps russia','Competitor/irrelevant geo.'),
('mapsnearme','toll free number directory scam','Scam intent.'),
('mapsnearme','business for sale','Marketplace intent — nahi.'),
('mapsnearme','jobs near me','Job portal intent — nahi serve karte.'),
('mapsnearme','matrimony near me','Matrimony intent — nahi.'),
('mapsnearme','property dealer contact list buy','Data-buying intent — nahi.'),
('mapsnearme','dhaba cooking recipe','Recipe intent — content mismatch.');
