-- Seed keywords for digipincode (positive + negative) with reasons.
-- Idempotent: INSERT OR IGNORE (UNIQUE(site, keyword) protects re-runs).
-- volume/difficulty later filled from GSC data.

-- ===== POSITIVE (target these) =====
INSERT OR IGNORE INTO keywords (site, keyword, intent, cluster, status, notes) VALUES
('digipincode','digipin','info','digipin','planned','Brand-match domain. India Post ka naya Digital Address system — low competition, high upside. TOP PRIORITY.'),
('digipincode','what is digipin','info','digipin','planned','Naya topic, educational content easy to rank. digipin cluster ka entry point.'),
('digipincode','digipin india post','navigational','digipin','planned','India Post official system queries — humara data unique hai.'),
('digipincode','digipin code locator','info','digipin','planned','Tool-intent search — future tool page target.'),
('digipincode','digipin vs pincode','info','digipin','planned','Comparison content — confusion-phase queries, early-mover advantage.'),
('digipincode','india pincode directory','info','pincode-core','planned','Head term for the whole site.'),
('digipincode','[village] pincode','info','pincode-core','planned','PATTERN: core long-tail — 155k village pages isi se serve hoti hain. Sabse bada traffic engine.'),
('digipincode','[pincode] villages list','info','pincode-core','planned','PATTERN: reverse lookup — hamara pincode page isi intent ko serve karta hai.'),
('digipincode','[pincode] post office name','info','pincode-core','planned','office_name data hamare paas hai — direct answer possible.'),
('digipincode','post office list [district]','info','pincode-core','planned','District-level directory queries.'),
('digipincode','[state] all pincodes list','info','pincode-core','planned','State-level list pages — high volume aggregate.'),
('digipincode','village lgd code','info','lgd-data','planned','Govt LGD code data — almost no competition, unique dataset.'),
('digipincode','lgd code search','info','lgd-data','planned','LGD lookup intent — panchayat/village dono cover.'),
('digipincode','[district] villages list','info','lgd-data','planned','Village directory per district.'),
('digipincode','[block] panchayat list','info','lgd-data','planned','Panchayat listing pages — LGD data unique selling point.'),
('digipincode','[tehsil] villages','info','lgd-data','planned','Sub-district level queries — long-tail, low competition.'),
('digipincode','[district] sub district list','info','lgd-data','planned','Blocks/tehsils directory.'),
('digipincode','pincode to digipin converter','transactional','tools','planned','Future tool — DigiPIN visualization project se link.'),
('digipincode','digipin to pincode','info','tools','planned','Reverse converter — tool banta hai to strong internal linking.'),
('digipincode','india post office directory','info','pincode-core','planned','India Post directory intent — head term.'),
('digipincode','nearest post office [village]','info','local','planned','Local intent — mapsnearme se overlap, but pincode page serve kar sakta hai.'),
('digipincode','[pincode] which district','info','pincode-core','planned','District/state lookup for a pincode — existing page covers it.'),
('digipincode','chhath ghat [city] list','info','seasonal','planned','Q4 seasonal — mid-Oct deadline, 300+ ghat pages planned.'),
('digipincode','chhath puja ghat near me','info','seasonal','planned','Seasonal spike Oct-Nov — early pages = ranking by festival.'),
('digipincode','[pincode] near which city','info','pincode-core','planned','Geo-context queries for village/pincode pages.'),
('digipincode','how many villages in [district]','info','lgd-data','planned','Stats queries — data-backed content easy to generate.'),
('digipincode','[village] population','info','census','planned','Census data combine karke village pages enrich — future phase.'),
('digipincode','[panchayat] villages list','info','lgd-data','planned','Panchayat ke under villages — LGD join se serve hota hai.'),
('digipincode','ap all village names list','info','lgd-data','planned','State-wide name lists — high volume.'),
('digipincode','up district wise villages list','info','lgd-data','planned','UP-like states mein bade search volumes.'),
('digipincode','[state] tehsil list','info','lgd-data','planned','Sub-district directory state-wise.'),
('digipincode','pincode full form','info','pincode-core','planned','Educational query — quick win FAQ content.'),
('digipincode','how pincode works in india','info','pincode-core','planned','Explainer content — internal linking hub.'),
('digipincode','[pincode] area name','info','pincode-core','planned','Area served by pincode — existing data covers.'),
('digipincode','6 digit pincode meaning','info','pincode-core','planned','Structure explainer — featured snippet target.'),
('digipincode','[village] in which district','info','lgd-data','planned','Village-to-district lookup.'),
('digipincode','[village] in which state','info','lgd-data','planned','Village-to-state lookup — trivia-intent traffic.'),
('digipincode','pincode zone [digit]','info','pincode-core','planned','First-digit zone explainer — unique structured content.'),
('digipincode','military address pincode','info','digipin','planned','DigiPIN defense/military address angle — very low competition.'),
('digipincode','[city] pincode list pdf alternative','info','pincode-core','planned','PDF-download intent ko HTML list se serve — better UX than PDF sites.')
;

-- ===== NEGATIVE (do NOT target) =====
INSERT OR IGNORE INTO negative_keywords (site, keyword, reason) VALUES
('digipincode','us zip code','Non-India geography — hamara data India-only hai.'),
('digipincode','uk postal code','Non-India — irrelevant traffic.'),
('digipincode','canada postal code lookup','Non-India geography.'),
('digipincode','nepal pin code','Non-India — border content Raxaul context mein alag se handle hoga, target nahi.'),
('digipincode','pakistan postal code','Non-India, zero data.'),
('digipincode','pincode excel download','Scraper intent — high bandwidth, zero engagement, bad UX metrics.'),
('digipincode','pincode database download free','Dataset scrapers — bounce rate high. Baad mein controlled download page ban sakte hain, abhi nahi.'),
('digipincode','pincode csv file','Same scraper intent as excel.'),
('digipincode','pincode api','Developer intent — hum API offer nahi karte. Baad mein alag product ban sake, abhi nahi.'),
('digipincode','india post api','Developer intent — product mismatch.'),
('digipincode','speed post tracking','Tracking service intent — hum directory hain, tracker nahi. Serve nahi kar sakte intent.'),
('digipincode','track consignment india post','Same tracking mismatch.'),
('digipincode','india post parcel charges','Pricing intent — live data nahi hai humare paas.'),
('digipincode','ifsc code [bank]','Banking code system — alag dataset (examstatus/tools territory, not pincode DB).'),
('digipincode','micr code','Banking — not our data.'),
('digipincode','swift code [bank]','Banking — not our data.'),
('digipincode','gst state code list','Tax code system — alag govt code, not postal.'),
('digipincode','rto vehicle code','Transport code system — alag dataset, future site idea but not here.'),
('digipincode','std code [city]','Telecom codes — not in DB; alag utility site idea later.'),
('digipincode','railway station code','Railway codes — different system.'),
('digipincode','pin code movie','Entertainment intent — irrelevance se bounce.'),
('digipincode','pincode app download','App intent — hum web hain, app nahi.'),
('digipincode','pincode whatsapp group link','Spam intent.'),
('digipincode','pincode loan','Financial spam — irrelevant.'),
('digipincode','sarkari result [pincode]','Exam intent — examstatus ka territory, yahan nahi.'),
('digipincode','courier service near me','Local business intent — mapsnearme territory, digipincode nahi.'),
('digipincode','pincode of birth certificate','Document intent — govt services, not directory.'),
('digipincode','aadhaar center pincode','Enrollment center data nahi hai — serve nahi kar sakte.'),
('digipincode','voter id office pincode','Same — data nahi.'),
('digipincode','pincode kya hai movie song','Entertainment noise.')
;
