CREATE TABLE IF NOT EXISTS trending_queries (query TEXT PRIMARY KEY, interest INTEGER DEFAULT 0, growth_pct INTEGER DEFAULT 0, source TEXT DEFAULT '', added_at TEXT DEFAULT (datetime('now')));
INSERT OR REPLACE INTO trending_queries (query, interest, growth_pct, source) VALUES
('my pincode',100,30,'top+rising'),
('pin code',100,4,'top'),
('delhi pincode',76,90,'top+rising'),
('pincode delhi',73,10,'top+rising'),
('noida pincode',52,40,'top+rising'),
('my location pincode',47,40,'top'),
('bangalore pincode',45,8,'top+rising'),
('pincode to pincode distance',42,30,'top+rising'),
('hyderabad pincode',41,20,'top'),
('chennai pincode',40,10,'top+rising'),
('mumbai pincode',37,90,'top+rising'),
('pincode of my location',35,30,'top'),
('current pincode',33,10,'top'),
('gurgaon pincode',33,3,'top'),
('jaipur pincode',32,10,'top+rising'),
('pune pincode',31,20,'top'),
('coimbatore pincode',31,4,'top+rising'),
('pincode distance',28,9,'top'),
('ahmedabad pincode',27,20,'top+rising'),
('lucknow pincode',27,10,'top+rising'),
('pincode near me',26,20,'top'),
('surat pincode',24,10,'top+rising'),
('current location pincode',22,20,'top+rising'),
('chandigarh pincode',22,5,'top+rising'),
('haryana pincode',22,5,'top+rising'),
('indore pincode',20,20,'top+rising'),
('kolkata pincode',19,10,'top+rising'),
('new delhi pincode',18,60,'top+rising'),
('bhopal pincode',18,30,'top+rising'),
('kanpur pincode',18,30,'top+rising'),
('digipin code',18,5,'top+rising'),
('mohali pincode',17,10,'top+rising'),
('vadodara pincode',16,60,'top+rising'),
('madurai pincode',16,8,'top+rising'),
('my current location pincode',15,30,'top'),
('patna pincode',14,4,'top'),
('ranchi pincode',13,30,'top+rising'),
('vijayawada pincode',13,30,'top+rising'),
('dehradun pincode',13,20,'top+rising'),
('faridabad pincode',13,10,'top+rising'),
('ghaziabad pincode',13,10,'top'),
('bengaluru pincode',12,30,'top+rising'),
('trichy pincode',12,10,'top'),
('salem pincode',12,7,'top'),
('gurugram pincode',12,6,'top+rising'),
('banglore pincode',11,20,'top+rising'),
('ludhiana pincode',11,20,'top+rising'),
('raipur pincode',11,10,'top+rising'),
('greater noida pincode',11,9,'top'),
('malappuram pincode',10,60,'top+rising'),
('nagpur pincode',10,40,'top+rising'),
('agra pincode',10,1,'top'),
('ahemdabad pincode',9,20,'rising'),
('tirunelveli pincode',9,20,'top+rising'),
('guntur pincode',9,10,'top'),
('kota pincode',9,9,'rising'),
('bareilly pincode',8,110,'rising'),
('dtdc pincode',8,7,'top+rising'),
('karur pincode',7,30,'rising'),
('kakkanad pincode',6,110,'rising'),
('mumbai pin code',6,30,'rising'),
('prayagraj pincode',6,10,'rising'),
('kharar pincode',5,30,'rising'),
('tiruppur pincode',5,20,'rising'),
('dharmapuri pincode',5,10,'rising'),
('tirupati pincode',5,1,'top'),
('ottapalam pincode',4,250,'rising'),
('nagercoil pincode',4,40,'rising'),
('201301 pincode',4,30,'rising'),
('aluva pincode',4,30,'rising'),
('shamshabad pincode',4,20,'rising'),
('vellore pincode',4,20,'top+rising'),
('tirur pincode',4,10,'rising'),
('nashik pincode',4,8,'top+rising'),
('thane pincode',4,5,'top'),
('visakhapatnam pincode',4,5,'top'),
('erode pincode',4,4,'top'),
('gachibowli pincode',4,1,'top'),
('sivakasi pincode',3,150,'rising'),
('gandimaisamma pincode',3,90,'rising'),
('attapur pincode',3,80,'rising'),
('baner pincode',3,60,'rising'),
('ameerpet pincode',3,40,'rising'),
('mayiladuthurai pincode',3,20,'rising'),
('thiruvallur pincode',3,20,'rising'),
('bachupally pincode',3,10,'rising'),
('dindigul pincode',3,10,'top+rising'),
('thanjavur pincode',3,9,'top+rising'),
('hosur pincode',3,6,'rising'),
('marathahalli pincode',3,6,'rising'),
('tirupur pincode',3,4,'top'),
('trivandrum pincode',3,4,'top'),
('kollam pincode',3,1,'top'),
('edappal pincode',2,3450,'rising');
SELECT COUNT(*) AS total FROM trending_queries;
